default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: upme_dev
  username: root
  password: root

test:
  <<: *default
  database: upme_test

production:
  url: <%= ENV['DATABASE_URL'] %>
