# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create!(email: 'admin@upme.com', password: 'secret')

coach = Coach.create(email: 'treinador@upme.com', password: 'secret', name: 'Treinador 1')
group = Group.create(coach: coach, name: 'Turma de futsal sub23', description: 'obs: quadra coberta toda quarta e sexta')
user1  = User.create(group: group, name: 'Nicolas Lima', age: 22, gender: :male, started_training_at: Date.today, email: 'nicolas@upme.com')

user1.vo2max_trainings.create distance: 2340, training_date: (Date.today - 14.day)
user1.vo2max_trainings.create distance: 2400, training_date: (Date.today - 13.day)
user1.vo2max_trainings.create distance: 2320, training_date: (Date.today - 12.day)
user1.vo2max_trainings.create distance: 2340, training_date: (Date.today - 11.day)
user1.vo2max_trainings.create distance: 2330, training_date: (Date.today - 10.day)
user1.vo2max_trainings.create distance: 2360, training_date: (Date.today - 9.day)
user1.vo2max_trainings.create distance: 2390, training_date: (Date.today - 8.day)
user1.vo2max_trainings.create distance: 2400, training_date: (Date.today - 7.day)
user1.vo2max_trainings.create distance: 2370, training_date: (Date.today - 6.day)
user1.vo2max_trainings.create distance: 2400, training_date: (Date.today - 5.day)
user1.vo2max_trainings.create distance: 2420, training_date: (Date.today - 4.day)
user1.vo2max_trainings.create distance: 2393, training_date: (Date.today - 3.day)
user1.vo2max_trainings.create distance: 2393, training_date: (Date.today - 2.day)
user1.vo2max_trainings.create distance: 2393, training_date: (Date.today - 1.day)
user1.vo2max_trainings.create distance: 2398, training_date: (Date.today)

group2 = Group.create(coach: coach, name: 'Turma de basquete sub23', description: 'obs: utilizar a pista do ginásio para as avaliações')
user2  = User.create(group: group2, name: 'Fulano Silva', age: 22, gender: :male, started_training_at: Date.today, email: 'fulano@upme.com')
user2.vo2max_trainings.create distance: 2340, training_date: (Date.today)
user2.vo2max_trainings.create distance: 2400, training_date: (Date.today - 1.day)
user2.vo2max_trainings.create distance: 2320, training_date: (Date.today - 2.day)
user2.vo2max_trainings.create distance: 2340, training_date: (Date.today - 3.day)
user2.vo2max_trainings.create distance: 2330, training_date: (Date.today - 4.day)
user2.vo2max_trainings.create distance: 2360, training_date: (Date.today - 5.day)
user2.vo2max_trainings.create distance: 2390, training_date: (Date.today - 6.day)
user2.vo2max_trainings.create distance: 2400, training_date: (Date.today - 7.day)
user2.vo2max_trainings.create distance: 2370, training_date: (Date.today - 8.day)
user2.vo2max_trainings.create distance: 2400, training_date: (Date.today - 9.day)
user2.vo2max_trainings.create distance: 2420, training_date: (Date.today - 10.day)
user2.vo2max_trainings.create distance: 2393, training_date: (Date.today - 11.day)
user2.vo2max_trainings.create distance: 2393, training_date: (Date.today - 12.day)
user2.vo2max_trainings.create distance: 2393, training_date: (Date.today - 13.day)
user2.vo2max_trainings.create distance: 2398, training_date: (Date.today - 14.day)
# group2 = Group.create(coach: coach, name: 'Turma de basquete sub23', description: 'obs: utilizar a pista do ginásio para as avaliações')
# user2  = User.create(group: group2, name: 'Fulano Silva', age: 22, gender: :male, started_training_at: Date.today, email: 'fulano@upme.com')
# user2.vo2max_trainings.create distance: 2190, training_date: (Date.today - 14.day)
# user2.vo2max_trainings.create distance: 2195, training_date: (Date.today - 13.day)
# user2.vo2max_trainings.create distance: 2192, training_date: (Date.today - 12.day)
# user2.vo2max_trainings.create distance: 2190, training_date: (Date.today - 11.day)
# user2.vo2max_trainings.create distance: 2195, training_date: (Date.today - 10.day)
# user2.vo2max_trainings.create distance: 2190, training_date: (Date.today - 9.day)
# user2.vo2max_trainings.create distance: 2188, training_date: (Date.today - 8.day)
# user2.vo2max_trainings.create distance: 2186, training_date: (Date.today - 7.day)
# user2.vo2max_trainings.create distance: 2186, training_date: (Date.today - 6.day)
# user2.vo2max_trainings.create distance: 2188, training_date: (Date.today - 5.day)
# user2.vo2max_trainings.create distance: 2190, training_date: (Date.today - 4.day)
# user2.vo2max_trainings.create distance: 2193, training_date: (Date.today - 3.day)
# user2.vo2max_trainings.create distance: 2193, training_date: (Date.today - 2.day)
# user2.vo2max_trainings.create distance: 2195, training_date: (Date.today - 1.day)
# user2.vo2max_trainings.create distance: 2198, training_date: (Date.today)
